### ISSUE TITLE
Add Python backend

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingo#21]
@petervdonovan did you say you could provide a Python backend for lingo. For the initial version of `lingo` only a very shallow shell around `lfc` is needed.

**Comment by petervdonovan** [comment]
Unfortunately I do not think I will have time for this in the near future unless it is difficult for someone else to do this. Apologies for not unassigning myself earlier.

**Comment by erlingrj** [comment]
A simple fix is to just add an example `HelloPy.lf` file in defaults and point to it in `lingo` and we have basic Python support
