### ISSUE TITLE
Lingo 0.2.0 Release

### ISSUE THREAD

**Issue by tanneberger** [lf-lang/lingo#34]
# Lingo 0.2.0 Release

**Deadline:** 30.9
- [x] #32 
- [x] [This](https://github.com/lf-lang/lingua-franca/pull/1686/) needs to be a little reworked so target properties are merged on lfc site and are not just treated as command line parameters. **SOMEBODY NEEDED** @lhstrh 
- [x] proper testing @cmnrd @lhstrh @revol-xut 
- [x] crates.io release @revol-xut

**Comment by lhstrh** [comment]
Completed!
