### ISSUE TITLE
lingo build fails on HelloWorld C because invalid JSON string

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingo#36]
```
Building ...
Running "/home/erling/tools/lingua-franca/build/install/lf-cli/bin/lfc" "--json={\"out\":\"/home/erling/dev/lf/lf-ex/my-synth/target\",\"properties\":{\"no-compile\":false},\"src\":\"/home/erling/dev/lf/lf-ex/my-synth/./src/Main.lf\"}"
Unmatched argument at index 4: 'false'

```

I think it might be because --no-compile=false is not a valid command line argument. If you want to invoke the target compiler, just dont pass any --no-compile arg

**Comment by revol-xut** [comment]
This is a huge problem with lfc. 

The `properties` field is getting handled wrong. All the fields in properties are getting treated as command line parameters and not for example not target properties.

**Comment by lhstrh** [comment]
> This is a huge problem with lfc.
> 
> The `properties` field is getting handled wrong. All the fields in properties are getting treated as command line parameters and not for example not target properties.

Could you clarify what the desired would be?

**Comment by lhstrh** [comment]
> This is a huge problem with lfc.
> 
> The `properties` field is getting handled wrong. All the fields in properties are getting treated as command line parameters and not for example not target properties.

I will go ahead and address this in https://github.com/lf-lang/lingua-franca/pull/2008.

**Comment by lhstrh** [comment]
This hinges on https://github.com/lf-lang/lingua-franca/pull/2035 and associated PRs that I'm still working on.

**Comment by lhstrh** [comment]
Since https://github.com/lf-lang/lingua-franca/pull/2008 has been merged, these problems should be fixed. There was a bug that ignored the output directory, but that is fixed in https://github.com/lf-lang/lingua-franca/pull/2088.
