### ISSUE TITLE
JSON interface between `lingo` and `lfc`

### ISSUE THREAD

**Issue by revol-xut** [lf-lang/lingo#4]
```json
{
	"src": "/home/revol-xut/workspace/lf-test/src/main.lf",
	"out": "/home/revol-xut/workspace/lf-test/src-gen",
	"properties": {
		"fast": true,
		"federated": true
	}
}
```

```
lfc --json '{...}'
lfc --json-file ./src-gen-ops.json
```

**Comment by revol-xut** [comment]
Do we also want to define which properties exist or do we want to leave this arbitrary?

**Comment by revol-xut** [comment]
@lhstrh The question is should lingo validate the properties if they exist and if they have the correct datatype or should I just forward all properties to lfc?

**Comment by revol-xut** [comment]
I am fully on your site there having the validation logic in two places is too much maintenance work and not a good style (a single point of truth is preferable). 

The reason why I asked was that there are maybe properties that are required for lfc to run. I am here for example thinking about things like a target (in case we want to move it out of the lf-file).  Lingo should complain about if those properties are not specified or default them to some value.  

I took a list at our docs: https://www.lf-lang.org/docs/handbook/target-declaration?target=c

But currently, we don't have any necessary properties so no real need to specify and include some in our specifications.

**Comment by patilatharva** [comment]
I have a followup question regarding the json format - how would be expect the `src` field to look if we have multiple input paths? If it's an array, should we also put single-file values in array for consistency?

**Comment by revol-xut** [comment]
@patilatharva what do you mean with multiple input paths ? In this suggestion src would point to the file that contains the main reactor and for building multiple programs at once I would invoke lfc multiple times with different values for src.

**Comment by patilatharva** [comment]
Yes, I meant for building multiple programs, but that makes sense. The `lfc` CLI supports multiple input paths at once so I was wondering whether we'd want that feature here too.

**Comment by revol-xut** [comment]
No I would say this lfc feature is useless for our use-case.

**Comment by lhstrh** [comment]
More specifically, I think the `json` flag should be mutually exclusive with any other parameters, no? This would sure make things simpler.
